name: Deploy Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract short SHA
      id: sha
      run: echo "short_sha=${GITHUB_SHA:0:7}"

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: 995596895848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:frontend-app-${{ steps.sha.outputs.short_sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        input: /tmp/image.tar
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        scan-type: 'image'
        exit-code: 0
      continue-on-error: true

    - name: Debug - Check if SARIF file exists
      run: |
        echo "=== Current directory contents ==="
        ls -la
        echo "=== Checking for SARIF file ==="
        if [ -f trivy-results.sarif ]; then
          echo "✅ SARIF file found"
          echo "File size: $(wc -c < trivy-results.sarif) bytes"
        else
          echo "❌ SARIF file not found in current directory"
          echo "=== Checking entire workspace ==="
          find . -name "*.sarif" -type f 2>/dev/null || echo "No SARIF files found"
        fi

    - name: Validate and prepare SARIF file
      run: |
        if [ -f trivy-results.sarif ]; then
          echo "=== SARIF File Details ==="
          echo "File size: $(wc -c < trivy-results.sarif) bytes"
          echo "Results found: $(jq -r '.runs[0].results | length' trivy-results.sarif)"
          
          # Ensure proper SARIF structure
          jq '
            .runs[0].tool.driver.name = "Trivy" |
            .runs[0].tool.driver.informationUri = "https://github.com/aquasecurity/trivy" |
            .runs[0].automationDetails = {"id": "trivy-scan"}
          ' trivy-results.sarif > trivy-results-fixed.sarif
          
          mv trivy-results-fixed.sarif trivy-results.sarif
          echo "✅ SARIF file prepared for GitHub"
        else
          echo "⚠️ SARIF file not found - creating empty SARIF file"
          # Create an empty SARIF file with proper structure
          cat > trivy-results.sarif << 'EOF'
{
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Trivy",
          "informationUri": "https://github.com/aquasecurity/trivy"
        }
      },
      "automationDetails": {
        "id": "trivy-scan"
      },
      "results": []
    }
  ]
}
EOF
          echo "✅ Empty SARIF file created"
        fi

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        category: 'trivy'
        wait-for-processing: false

    - name: Debug - Show upload result
      run: |
        echo "=== Upload Status ==="
        echo "If no errors above, check GitHub Security tab in 2-5 minutes"
        echo "Location: https://github.com/${{ github.repository }}/security/code-scanning"

    - name: Check for critical vulnerabilities
      id: scan-check
      run: |
        if [ -f trivy-results.sarif ]; then
          COUNT=$(jq -r '.runs[0].results | length' trivy-results.sarif 2>/dev/null || echo "0")
          if [ "$COUNT" -gt 0 ]; then
            echo "❌ Found $COUNT vulnerabilities in the image"
            echo "=== Sample Vulnerabilities ==="
            jq -r '.runs[0].results[0:3][] | "\(.level): \(.ruleId) - \(.message.text)"' trivy-results.sarif
            echo "scan_status=failed" 
            echo "vulnerability_count=$COUNT"
            exit 1
          else
            echo "✅ No critical vulnerabilities found"
            echo "scan_status=passed" 
            echo "vulnerability_count=0"
          fi
        else
          echo "❌ Scan results not found"
          echo "scan_status=error" 
          exit 1
        fi

    - name: Push Docker image to ECR
      if: steps.scan-check.outputs.scan_status == 'passed'
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: 995596896848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:frontend-app-${{ steps.sha.outputs.short_sha }}
        cache-from: type=gha

    - name: Verify pushed image
      if: steps.scan-check.outputs.scan_status == 'passed'
      run: |
        echo "Frontend Docker image pushed to ECR successfully"
        echo "Full SHA: ${{ github.sha }}"
        echo "Short SHA: ${{ steps.sha.outputs.short_sha }}"
        echo "Repository: 995596896848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:frontend-app-${{ steps.sha.outputs.short_sha }}"

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: |
          ${{ job.status == 'success' && '✅ SUCCESS: Frontend Deployment' || '❌ FAILED: Frontend Deployment' }}
          - ${{ github.repository }} - ${{ github.ref_name }}
        to: ${{ secrets.NOTIFICATION_EMAILS }}
        from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
        body: |
          Frontend Docker Image Build and Deployment Result
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit SHA: ${{ github.sha }} (${{ steps.sha.outputs.short_sha }})
          Workflow: ${{ github.workflow }}
          Triggered by: ${{ github.actor }}
          
          Build Status: ${{ job.status }}
          ${{ steps.scan-check.outputs.scan_status && format('Security Scan: {0}', steps.scan-check.outputs.scan_status) || 'Security Scan: Not completed' }}
          ${{ steps.scan-check.outputs.vulnerability_count && format('Vulnerabilities Found: {0}', steps.scan-check.outputs.vulnerability_count) || '' }}
          
          ${{ job.status == 'success' && '✅ Image successfully built, scanned, and pushed to ECR' || '❌ Deployment failed - check workflow logs for details' }}
          
          Image Tag: 995596896848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:frontend-app-${{ steps.sha.outputs.short_sha }}
          
          View workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}