name: Deploy Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          zenzebz/frontend-app:${{ github.sha }}
          zenzebz/frontend-app:latest
          zenzebz/frontend-app:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify pushed image
      run: |
        echo "Frontend Docker image pushed successfully for SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"