name: Deploy CD - Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Frontend CI with CodeQL", "Backend CI"]
    types:
      - completed
  # Manual trigger for deployment
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          zenzebz/frontend-app
          zenzebz/backend-app
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Frontend Docker image
      if: contains(github.event.workflow_run.name, 'Frontend') || github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: zenzebz/frontend-app:${{ github.sha }}, zenzebz/frontend-app:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Backend Docker image
      if: contains(github.event.workflow_run.name, 'Backend') || github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: zenzebz/backend-app:${{ github.sha }}, zenzebz/backend-app:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify pushed images
      run: |
        echo "Docker images pushed successfully:"
        echo "- zenzebz/frontend-app:${{ github.sha }}"
        echo "- zenzebz/backend-app:${{ github.sha }}"
        echo "- zenzebz/frontend-app:latest"
        echo "- zenzebz/backend-app:latest"