name: Deploy Frontend
on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
  workflow_dispatch:
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and push Frontend Docker image to ECR
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: 995596895848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify pushed image
      run: |
        echo "Frontend Docker image pushed to ECR successfully for SHA: ${{ github.sha }}"
        echo "Repository: 995596895848.dkr.ecr.ca-central-1.amazonaws.com/drivelink/engaged:${{ github.sha }}"